version: 2.1
orbs:
  win: circleci/windows@5.1.0

jobs:
  build:
    parameters:
      static:
        type: boolean
    executor: win/server-2022
    steps:
      - checkout

      - run:
          name: Install vcpkg and dependencies
          command: |
            if (-not (Test-Path 'C:/tools/vcpkg')) {
              git clone https://github.com/microsoft/vcpkg C:/tools/vcpkg
              & C:/tools/vcpkg/bootstrap-vcpkg.bat
            }
            if (<<parameters.static>>) {
              & C:/tools/vcpkg/vcpkg install ffmpeg[dav1d,openh264,x264,x265,mp3lame,fdk-aac,opus,zlib,ffmpeg]:x64-windows-static
              & C:/tools/vcpkg/vcpkg install curl[core,sspi,ssl,schannel,non-http]:x64-windows-static
            }

      - when:
          condition:
            not: <<parameters.static>>
          steps:
            - run:
                name: Install FFmpeg (dynamic)
                command: |
                  New-Item -ItemType Directory -Force -Path "C:/Program Files/ffmpeg"
                  $url = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip"
                  $zipPath = "C:/ffmpeg.zip"
                  Invoke-WebRequest -Uri $url -OutFile $zipPath
                  $tempExtractDir = "C:/ffmpeg_temp"
                  Expand-Archive -Path $zipPath -DestinationPath $tempExtractDir
                  $unzipped = Get-ChildItem -Path $tempExtractDir | Select-Object -First 1
                  Move-Item -Path (Join-Path $unzipped.FullName "*") -Destination "C:/Program Files/ffmpeg"
                  Remove-Item $zipPath
                  Remove-Item $tempExtractDir -Recurse

      - run:
          name: Install CMake via Chocolatey
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
            refreshenv
            cmake --version

      - run:
          name: Configure
          command: |
            if (<<parameters.static>>) {
              $env:FFMPEG_ROOT = "C:/tools/vcpkg/installed/x64-windows-static"
              $env:CURL_ROOT   = "C:/tools/vcpkg/installed/x64-windows-static"
              $env:CMAKE_TOOLCHAIN_FILE = "C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
              $buildDir = "build-static";  $flag = "ON"
            } else {
              $env:FFMPEG_ROOT = "C:/Program Files/ffmpeg"
              $env:CURL_ROOT   = "vendor/libcurl"
              $buildDir = "build";         $flag = "OFF"
            }
            cmake -S . -B $buildDir -A x64 `
                  -DUSE_STATIC_FFMPEG=$flag `
                  -DFFMPEG_ROOT="$env:FFMPEG_ROOT" `
                  -DCURL_ROOT="$env:CURL_ROOT"

      - run:
          name: Build
          command: |
            if (<<parameters.static>>) { $buildDir = "build-static" } else { $buildDir = "build" }
            cmake --build $buildDir --config Release

workflows:
  build:
    jobs:
      - build:
          name: build-dynamic
          static: false
      - build:
          name: build-static
          static: true
