version: 2.1
orbs:
  win: circleci/windows@5.1.0

jobs:
  build:
    parameters:
      static:
        type: boolean
    executor: win/server-2022
    steps:
      - checkout

      - restore_cache:
          keys:
            - vcpkg-cache-{{ checksum "vcpkg.json" }}
            - vcpkg-cache-

      - run:
          name: Install vcpkg and dependencies
          shell: powershell
          command: |
            if (-not (Test-Path 'C:/tools/vcpkg')) {
              git clone https://github.com/microsoft/vcpkg C:/tools/vcpkg
              & C:/tools/vcpkg/bootstrap-vcpkg.bat
            }

            # Habilitar caché binario interno
            $env:VCPKG_DEFAULT_BINARY_CACHE = "C:/tools/vcpkg/bincache"
            if (-not (Test-Path $env:VCPKG_DEFAULT_BINARY_CACHE)) {
              New-Item -ItemType Directory -Force -Path $env:VCPKG_DEFAULT_BINARY_CACHE | Out-Null
            }

            if ("<<parameters.static>>" -eq "true") {
              & C:/tools/vcpkg/vcpkg install ffmpeg[dav1d,openh264,x264,x265,mp3lame,fdk-aac,opus,zlib,ffmpeg]:x64-windows-static
              & C:/tools/vcpkg/vcpkg install curl[core,sspi,ssl,schannel,non-http]:x64-windows-static
            }

      - save_cache:
          key: vcpkg-cache-{{ checksum "vcpkg.json" }}
          paths:
            - C:/tools/vcpkg

      - when:
          condition:
            not: <<parameters.static>>
          steps:
            - run:
                name: Install FFmpeg (dynamic)
                shell: powershell
                command: |
                  New-Item -ItemType Directory -Force -Path "C:/Program Files/ffmpeg"
                  $url = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip"
                  $zipPath = "C:/ffmpeg.zip"
                  Invoke-WebRequest -Uri $url -OutFile $zipPath
                  $tempExtractDir = "C:/ffmpeg_temp"
                  Expand-Archive -Path $zipPath -DestinationPath $tempExtractDir
                  $unzipped = Get-ChildItem -Path $tempExtractDir | Select-Object -First 1
                  Move-Item -Path (Join-Path $unzipped.FullName "*") -Destination "C:/Program Files/ffmpeg"
                  Remove-Item $zipPath
                  Remove-Item $tempExtractDir -Recurse

      - run:
          name: Install CMake via Chocolatey
          shell: powershell
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
            refreshenv
            cmake --version

      - run:
          name: Run build script
          shell: powershell
          command: |
            if ("<<parameters.static>>" -eq "true") {
              ./run.ps1 -Static
            } else {
              ./run.ps1
            }

      - store_artifacts:
          path: ./build/Release
          destination: release

workflows:
  ci-build:
    jobs:
      - build:
          name: build-dynamic
          static: false
      - build:
          name: build-static
          static: true
